CREATE TABLE general.tb_cita
(
    id_cita        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_cita     VARCHAR(255),
    hora_cita      VARCHAR(255),
    fecha_creacion VARCHAR(255),
    observacion    VARCHAR(255),
    id_usuario     INTEGER,
    id_mascota     INTEGER,
    CONSTRAINT pk_tb_cita PRIMARY KEY (id_cita)
);

CREATE TABLE general.tb_mascota
(
    id_mascota               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre                   VARCHAR(255),
    fecha_nacimiento         VARCHAR(255),
    genero                   VARCHAR(255),
    id_tipo_mascota          INTEGER,
    id_tipo_raza             INTEGER,
    peso                     DOUBLE PRECISION,
    fecha_ultima_vacunacion  VARCHAR(255),
    fecha_proxima_vacunacion VARCHAR(255),
    imagen                   VARCHAR(255),
    id_usuario               INTEGER,
    fecha_registro           VARCHAR(255),
    CONSTRAINT pk_tb_mascota PRIMARY KEY (id_mascota)
);

CREATE TABLE general.tb_tipo_documento
(
    id_tipo_documento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre            VARCHAR(255),
    CONSTRAINT pk_tb_tipo_documento PRIMARY KEY (id_tipo_documento)
);

CREATE TABLE general.tb_tipo_mascota
(
    id_tipo_mascota INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          VARCHAR(255),
    CONSTRAINT pk_tb_tipo_mascota PRIMARY KEY (id_tipo_mascota)
);

CREATE TABLE general.tb_tipo_raza
(
    id_tipo_raza INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       VARCHAR(255),
    CONSTRAINT pk_tb_tipo_raza PRIMARY KEY (id_tipo_raza)
);

CREATE TABLE general.tb_usuario
(
    id_usuario        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre            VARCHAR(255),
    apellidos         VARCHAR(255),
    id_tipo_documento INTEGER,
    nro_documento     VARCHAR(255),
    correo            VARCHAR(255),
    telefono          VARCHAR(255),
    username          VARCHAR(255),
    password          VARCHAR(255),
    fecha_registro    VARCHAR(255),
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id_usuario)
);

CREATE TABLE general.tb_veterinario
(
    id_veterinario INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         VARCHAR(255),
    codigo         VARCHAR(255),
    CONSTRAINT pk_tb_veterinario PRIMARY KEY (id_veterinario)
);

ALTER TABLE general.tb_cita
    ADD CONSTRAINT FK_TB_CITA_ON_ID_MASCOTA FOREIGN KEY (id_mascota) REFERENCES general.tb_mascota (id_mascota);

ALTER TABLE general.tb_cita
    ADD CONSTRAINT FK_TB_CITA_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES general.tb_usuario (id_usuario);

ALTER TABLE general.tb_mascota
    ADD CONSTRAINT FK_TB_MASCOTA_ON_ID_TIPO_MASCOTA FOREIGN KEY (id_tipo_mascota) REFERENCES general.tb_tipo_mascota (id_tipo_mascota);

ALTER TABLE general.tb_mascota
    ADD CONSTRAINT FK_TB_MASCOTA_ON_ID_TIPO_RAZA FOREIGN KEY (id_tipo_raza) REFERENCES general.tb_tipo_raza (id_tipo_raza);

ALTER TABLE general.tb_mascota
    ADD CONSTRAINT FK_TB_MASCOTA_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES general.tb_usuario (id_usuario);

ALTER TABLE general.tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_ID_TIPO_DOCUMENTO FOREIGN KEY (id_tipo_documento) REFERENCES general.tb_tipo_documento (id_tipo_documento);