server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://trolley.proxy.rlwy.net:20884/railway
    username: postgres
    password: lfUpYroLsmKeyRYybLZmsilxtiTQzIxn
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db_cibervet
#    username: postgres
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: cibervet
      password: 123456
