server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d0bml1juibrs73dg1elg-a.virginia-postgres.render.com:5432/db_cibervet
    username: db_cibervet_user
    password: 3JJ0QRlN7NMyFlmnBnm2T6mUGfvZn4nG
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db_cibervet
#    username: postgres
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: cibervet
      password: 123456
